// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDpEOAXnNwhYWUgg5cH58YFcsgH-19Bd0',
    appId: '1:679782356496:web:db4df7cdbe3fd6204c9c95',
    messagingSenderId: '679782356496',
    projectId: 'login-and-signup-project-a7671',
    authDomain: 'login-and-signup-project-a7671.firebaseapp.com',
    storageBucket: 'login-and-signup-project-a7671.firebasestorage.app',
    measurementId: 'G-37R2JFC9NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj7VRjuLyv2aSPI-nhhVpbp2Ew8mzVHn8',
    appId: '1:679782356496:android:726a9c7dd1e576bb4c9c95',
    messagingSenderId: '679782356496',
    projectId: 'login-and-signup-project-a7671',
    storageBucket: 'login-and-signup-project-a7671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjReJVPpkAl9vYWt5TBVAfVgZ1y_Np8hM',
    appId: '1:679782356496:ios:fa451818ce14acaf4c9c95',
    messagingSenderId: '679782356496',
    projectId: 'login-and-signup-project-a7671',
    storageBucket: 'login-and-signup-project-a7671.firebasestorage.app',
    iosBundleId: 'com.example.imageProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjReJVPpkAl9vYWt5TBVAfVgZ1y_Np8hM',
    appId: '1:679782356496:ios:fa451818ce14acaf4c9c95',
    messagingSenderId: '679782356496',
    projectId: 'login-and-signup-project-a7671',
    storageBucket: 'login-and-signup-project-a7671.firebasestorage.app',
    iosBundleId: 'com.example.imageProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDpEOAXnNwhYWUgg5cH58YFcsgH-19Bd0',
    appId: '1:679782356496:web:7977c5addd2cd7794c9c95',
    messagingSenderId: '679782356496',
    projectId: 'login-and-signup-project-a7671',
    authDomain: 'login-and-signup-project-a7671.firebaseapp.com',
    storageBucket: 'login-and-signup-project-a7671.firebasestorage.app',
    measurementId: 'G-EL7GETJNCJ',
  );
}
